// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package com.randioo.chat_server.protocol;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ChatJoinRoomRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use ChatJoinRoomRequest.newBuilder() to construct.
    private ChatJoinRoomRequest() {
      initFields();
    }
    private ChatJoinRoomRequest(boolean noInit) {}
    
    private static final ChatJoinRoomRequest defaultInstance;
    public static ChatJoinRoomRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatJoinRoomRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.chat_server.protocol.Chat.internal_static_com_randioo_chat_server_protocol_ChatJoinRoomRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.chat_server.protocol.Chat.internal_static_com_randioo_chat_server_protocol_ChatJoinRoomRequest_fieldAccessorTable;
    }
    
    // optional string roomId = 1;
    public static final int ROOMID_FIELD_NUMBER = 1;
    private boolean hasRoomId;
    private java.lang.String roomId_ = "";
    public boolean hasRoomId() { return hasRoomId; }
    public java.lang.String getRoomId() { return roomId_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRoomId()) {
        output.writeString(1, getRoomId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRoomId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getRoomId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest result;
      
      // Construct using com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest();
        return builder;
      }
      
      protected com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest.getDescriptor();
      }
      
      public com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest getDefaultInstanceForType() {
        return com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest) {
          return mergeFrom((com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest other) {
        if (other == com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest.getDefaultInstance()) return this;
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setRoomId(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string roomId = 1;
      public boolean hasRoomId() {
        return result.hasRoomId();
      }
      public java.lang.String getRoomId() {
        return result.getRoomId();
      }
      public Builder setRoomId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRoomId = true;
        result.roomId_ = value;
        return this;
      }
      public Builder clearRoomId() {
        result.hasRoomId = false;
        result.roomId_ = getDefaultInstance().getRoomId();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.chat_server.protocol.ChatJoinRoomRequest)
    }
    
    static {
      defaultInstance = new ChatJoinRoomRequest(true);
      com.randioo.chat_server.protocol.Chat.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.chat_server.protocol.ChatJoinRoomRequest)
  }
  
  public static final class ChatJoinRoomResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use ChatJoinRoomResponse.newBuilder() to construct.
    private ChatJoinRoomResponse() {
      initFields();
    }
    private ChatJoinRoomResponse(boolean noInit) {}
    
    private static final ChatJoinRoomResponse defaultInstance;
    public static ChatJoinRoomResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatJoinRoomResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.chat_server.protocol.Chat.internal_static_com_randioo_chat_server_protocol_ChatJoinRoomResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.chat_server.protocol.Chat.internal_static_com_randioo_chat_server_protocol_ChatJoinRoomResponse_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse result;
      
      // Construct using com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse();
        return builder;
      }
      
      protected com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse.getDescriptor();
      }
      
      public com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse getDefaultInstanceForType() {
        return com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse) {
          return mergeFrom((com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse other) {
        if (other == com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.chat_server.protocol.ChatJoinRoomResponse)
    }
    
    static {
      defaultInstance = new ChatJoinRoomResponse(true);
      com.randioo.chat_server.protocol.Chat.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.chat_server.protocol.ChatJoinRoomResponse)
  }
  
  public static final class ChatSendRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use ChatSendRequest.newBuilder() to construct.
    private ChatSendRequest() {
      initFields();
    }
    private ChatSendRequest(boolean noInit) {}
    
    private static final ChatSendRequest defaultInstance;
    public static ChatSendRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatSendRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.chat_server.protocol.Chat.internal_static_com_randioo_chat_server_protocol_ChatSendRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.chat_server.protocol.Chat.internal_static_com_randioo_chat_server_protocol_ChatSendRequest_fieldAccessorTable;
    }
    
    // optional .com.randioo.chat_server.protocol.ChatData chatData = 1;
    public static final int CHATDATA_FIELD_NUMBER = 1;
    private boolean hasChatData;
    private com.randioo.chat_server.protocol.Entity.ChatData chatData_;
    public boolean hasChatData() { return hasChatData; }
    public com.randioo.chat_server.protocol.Entity.ChatData getChatData() { return chatData_; }
    
    private void initFields() {
      chatData_ = com.randioo.chat_server.protocol.Entity.ChatData.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasChatData()) {
        output.writeMessage(1, getChatData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasChatData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getChatData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.chat_server.protocol.Chat.ChatSendRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.chat_server.protocol.Chat.ChatSendRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.chat_server.protocol.Chat.ChatSendRequest result;
      
      // Construct using com.randioo.chat_server.protocol.Chat.ChatSendRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.chat_server.protocol.Chat.ChatSendRequest();
        return builder;
      }
      
      protected com.randioo.chat_server.protocol.Chat.ChatSendRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.chat_server.protocol.Chat.ChatSendRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.chat_server.protocol.Chat.ChatSendRequest.getDescriptor();
      }
      
      public com.randioo.chat_server.protocol.Chat.ChatSendRequest getDefaultInstanceForType() {
        return com.randioo.chat_server.protocol.Chat.ChatSendRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.chat_server.protocol.Chat.ChatSendRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.chat_server.protocol.Chat.ChatSendRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.chat_server.protocol.Chat.ChatSendRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.chat_server.protocol.Chat.ChatSendRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.chat_server.protocol.Chat.ChatSendRequest) {
          return mergeFrom((com.randioo.chat_server.protocol.Chat.ChatSendRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.chat_server.protocol.Chat.ChatSendRequest other) {
        if (other == com.randioo.chat_server.protocol.Chat.ChatSendRequest.getDefaultInstance()) return this;
        if (other.hasChatData()) {
          mergeChatData(other.getChatData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.chat_server.protocol.Entity.ChatData.Builder subBuilder = com.randioo.chat_server.protocol.Entity.ChatData.newBuilder();
              if (hasChatData()) {
                subBuilder.mergeFrom(getChatData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.chat_server.protocol.ChatData chatData = 1;
      public boolean hasChatData() {
        return result.hasChatData();
      }
      public com.randioo.chat_server.protocol.Entity.ChatData getChatData() {
        return result.getChatData();
      }
      public Builder setChatData(com.randioo.chat_server.protocol.Entity.ChatData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatData = true;
        result.chatData_ = value;
        return this;
      }
      public Builder setChatData(com.randioo.chat_server.protocol.Entity.ChatData.Builder builderForValue) {
        result.hasChatData = true;
        result.chatData_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatData(com.randioo.chat_server.protocol.Entity.ChatData value) {
        if (result.hasChatData() &&
            result.chatData_ != com.randioo.chat_server.protocol.Entity.ChatData.getDefaultInstance()) {
          result.chatData_ =
            com.randioo.chat_server.protocol.Entity.ChatData.newBuilder(result.chatData_).mergeFrom(value).buildPartial();
        } else {
          result.chatData_ = value;
        }
        result.hasChatData = true;
        return this;
      }
      public Builder clearChatData() {
        result.hasChatData = false;
        result.chatData_ = com.randioo.chat_server.protocol.Entity.ChatData.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.chat_server.protocol.ChatSendRequest)
    }
    
    static {
      defaultInstance = new ChatSendRequest(true);
      com.randioo.chat_server.protocol.Chat.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.chat_server.protocol.ChatSendRequest)
  }
  
  public static final class ChatSendResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use ChatSendResponse.newBuilder() to construct.
    private ChatSendResponse() {
      initFields();
    }
    private ChatSendResponse(boolean noInit) {}
    
    private static final ChatSendResponse defaultInstance;
    public static ChatSendResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatSendResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.chat_server.protocol.Chat.internal_static_com_randioo_chat_server_protocol_ChatSendResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.chat_server.protocol.Chat.internal_static_com_randioo_chat_server_protocol_ChatSendResponse_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.chat_server.protocol.Chat.ChatSendResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.ChatSendResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.chat_server.protocol.Chat.ChatSendResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.chat_server.protocol.Chat.ChatSendResponse result;
      
      // Construct using com.randioo.chat_server.protocol.Chat.ChatSendResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.chat_server.protocol.Chat.ChatSendResponse();
        return builder;
      }
      
      protected com.randioo.chat_server.protocol.Chat.ChatSendResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.chat_server.protocol.Chat.ChatSendResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.chat_server.protocol.Chat.ChatSendResponse.getDescriptor();
      }
      
      public com.randioo.chat_server.protocol.Chat.ChatSendResponse getDefaultInstanceForType() {
        return com.randioo.chat_server.protocol.Chat.ChatSendResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.chat_server.protocol.Chat.ChatSendResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.chat_server.protocol.Chat.ChatSendResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.chat_server.protocol.Chat.ChatSendResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.chat_server.protocol.Chat.ChatSendResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.chat_server.protocol.Chat.ChatSendResponse) {
          return mergeFrom((com.randioo.chat_server.protocol.Chat.ChatSendResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.chat_server.protocol.Chat.ChatSendResponse other) {
        if (other == com.randioo.chat_server.protocol.Chat.ChatSendResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.chat_server.protocol.ChatSendResponse)
    }
    
    static {
      defaultInstance = new ChatSendResponse(true);
      com.randioo.chat_server.protocol.Chat.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.chat_server.protocol.ChatSendResponse)
  }
  
  public static final class SCChat extends
      com.google.protobuf.GeneratedMessage {
    // Use SCChat.newBuilder() to construct.
    private SCChat() {
      initFields();
    }
    private SCChat(boolean noInit) {}
    
    private static final SCChat defaultInstance;
    public static SCChat getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCChat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.chat_server.protocol.Chat.internal_static_com_randioo_chat_server_protocol_SCChat_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.chat_server.protocol.Chat.internal_static_com_randioo_chat_server_protocol_SCChat_fieldAccessorTable;
    }
    
    // optional .com.randioo.chat_server.protocol.ChatData chatData = 1;
    public static final int CHATDATA_FIELD_NUMBER = 1;
    private boolean hasChatData;
    private com.randioo.chat_server.protocol.Entity.ChatData chatData_;
    public boolean hasChatData() { return hasChatData; }
    public com.randioo.chat_server.protocol.Entity.ChatData getChatData() { return chatData_; }
    
    private void initFields() {
      chatData_ = com.randioo.chat_server.protocol.Entity.ChatData.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasChatData()) {
        output.writeMessage(1, getChatData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasChatData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getChatData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.chat_server.protocol.Chat.SCChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.SCChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.SCChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.SCChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.SCChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.SCChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.SCChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.chat_server.protocol.Chat.SCChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.chat_server.protocol.Chat.SCChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.chat_server.protocol.Chat.SCChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.chat_server.protocol.Chat.SCChat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.chat_server.protocol.Chat.SCChat result;
      
      // Construct using com.randioo.chat_server.protocol.Chat.SCChat.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.chat_server.protocol.Chat.SCChat();
        return builder;
      }
      
      protected com.randioo.chat_server.protocol.Chat.SCChat internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.chat_server.protocol.Chat.SCChat();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.chat_server.protocol.Chat.SCChat.getDescriptor();
      }
      
      public com.randioo.chat_server.protocol.Chat.SCChat getDefaultInstanceForType() {
        return com.randioo.chat_server.protocol.Chat.SCChat.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.chat_server.protocol.Chat.SCChat build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.chat_server.protocol.Chat.SCChat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.chat_server.protocol.Chat.SCChat buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.chat_server.protocol.Chat.SCChat returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.chat_server.protocol.Chat.SCChat) {
          return mergeFrom((com.randioo.chat_server.protocol.Chat.SCChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.chat_server.protocol.Chat.SCChat other) {
        if (other == com.randioo.chat_server.protocol.Chat.SCChat.getDefaultInstance()) return this;
        if (other.hasChatData()) {
          mergeChatData(other.getChatData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.chat_server.protocol.Entity.ChatData.Builder subBuilder = com.randioo.chat_server.protocol.Entity.ChatData.newBuilder();
              if (hasChatData()) {
                subBuilder.mergeFrom(getChatData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.chat_server.protocol.ChatData chatData = 1;
      public boolean hasChatData() {
        return result.hasChatData();
      }
      public com.randioo.chat_server.protocol.Entity.ChatData getChatData() {
        return result.getChatData();
      }
      public Builder setChatData(com.randioo.chat_server.protocol.Entity.ChatData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatData = true;
        result.chatData_ = value;
        return this;
      }
      public Builder setChatData(com.randioo.chat_server.protocol.Entity.ChatData.Builder builderForValue) {
        result.hasChatData = true;
        result.chatData_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatData(com.randioo.chat_server.protocol.Entity.ChatData value) {
        if (result.hasChatData() &&
            result.chatData_ != com.randioo.chat_server.protocol.Entity.ChatData.getDefaultInstance()) {
          result.chatData_ =
            com.randioo.chat_server.protocol.Entity.ChatData.newBuilder(result.chatData_).mergeFrom(value).buildPartial();
        } else {
          result.chatData_ = value;
        }
        result.hasChatData = true;
        return this;
      }
      public Builder clearChatData() {
        result.hasChatData = false;
        result.chatData_ = com.randioo.chat_server.protocol.Entity.ChatData.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.chat_server.protocol.SCChat)
    }
    
    static {
      defaultInstance = new SCChat(true);
      com.randioo.chat_server.protocol.Chat.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.chat_server.protocol.SCChat)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_chat_server_protocol_ChatJoinRoomRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_chat_server_protocol_ChatJoinRoomRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_chat_server_protocol_ChatJoinRoomResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_chat_server_protocol_ChatJoinRoomResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_chat_server_protocol_ChatSendRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_chat_server_protocol_ChatSendRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_chat_server_protocol_ChatSendResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_chat_server_protocol_ChatSendResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_chat_server_protocol_SCChat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_chat_server_protocol_SCChat_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nChat.proto\022 com.randioo.chat_server.pr" +
      "otocol\032\014Entity.proto\"%\n\023ChatJoinRoomRequ" +
      "est\022\016\n\006roomId\030\001 \001(\t\"\026\n\024ChatJoinRoomRespo" +
      "nse\"O\n\017ChatSendRequest\022<\n\010chatData\030\001 \001(\013" +
      "2*.com.randioo.chat_server.protocol.Chat" +
      "Data\"\022\n\020ChatSendResponse\"F\n\006SCChat\022<\n\010ch" +
      "atData\030\001 \001(\0132*.com.randioo.chat_server.p" +
      "rotocol.ChatData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_chat_server_protocol_ChatJoinRoomRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_chat_server_protocol_ChatJoinRoomRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_chat_server_protocol_ChatJoinRoomRequest_descriptor,
              new java.lang.String[] { "RoomId", },
              com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest.class,
              com.randioo.chat_server.protocol.Chat.ChatJoinRoomRequest.Builder.class);
          internal_static_com_randioo_chat_server_protocol_ChatJoinRoomResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_chat_server_protocol_ChatJoinRoomResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_chat_server_protocol_ChatJoinRoomResponse_descriptor,
              new java.lang.String[] { },
              com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse.class,
              com.randioo.chat_server.protocol.Chat.ChatJoinRoomResponse.Builder.class);
          internal_static_com_randioo_chat_server_protocol_ChatSendRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_chat_server_protocol_ChatSendRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_chat_server_protocol_ChatSendRequest_descriptor,
              new java.lang.String[] { "ChatData", },
              com.randioo.chat_server.protocol.Chat.ChatSendRequest.class,
              com.randioo.chat_server.protocol.Chat.ChatSendRequest.Builder.class);
          internal_static_com_randioo_chat_server_protocol_ChatSendResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_chat_server_protocol_ChatSendResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_chat_server_protocol_ChatSendResponse_descriptor,
              new java.lang.String[] { },
              com.randioo.chat_server.protocol.Chat.ChatSendResponse.class,
              com.randioo.chat_server.protocol.Chat.ChatSendResponse.Builder.class);
          internal_static_com_randioo_chat_server_protocol_SCChat_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_randioo_chat_server_protocol_SCChat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_chat_server_protocol_SCChat_descriptor,
              new java.lang.String[] { "ChatData", },
              com.randioo.chat_server.protocol.Chat.SCChat.class,
              com.randioo.chat_server.protocol.Chat.SCChat.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.chat_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
